# Generated by Django 5.0.1 on 2024-01-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_category_slug_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(upload_to="blogs"),
        ),
    ]
