# Generated by Django 5.0.1 on 2024-01-11 03:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
