# Generated by Django 5.0.1 on 2024-01-11 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_blog_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
    ]
